# Generated by Django 4.2.1 on 2023-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrudUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("phone", models.IntegerField(blank=True, max_length=10)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
