# Generated by Django 4.2.1 on 2023-05-11 11:55

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cruduser",
            name="phone",
            field=phone_field.models.PhoneField(blank=True, max_length=10),
        ),
    ]
